### ISSUE TITLE
0.15.1, phpdbg and Docker: zend_mm_heap corrupted

### ISSUE THREAD

**Issue by dkarlovi** [infection/infection#1038]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.15.1
| Test Framework version | PHPUnit 9
| PHP version | 7.2, 7.3, 7.4
| Platform    | Docker, `jakzal/phpqa-1.30-alpine`
| Github Repo | https://github.com/dkarlovi/xezilaires

Just a reminder about https://github.com/jakzal/phpqa/issues/200 which highlights the issue of 0.15.1 PHAR + phpdbg producing an error:

```
Generating code coverage report in PHPUnit XML format ... done
sh -c "  phpdbg -qrr /tools/infection run --verbose --show-mutations --no-interaction --only-covered --coverage var/ --min-msi=100 --min-covered-msi=100 --threads 4"
zend_mm_heap corrupted
```

**Comment by dkarlovi** [comment]
Works without phpdbg so I guess it's a super-specific corner case issue.

**Comment by dkarlovi** [comment]
So it only fails with PHPDBG + Github Actions + 0.15.1, but not with any other permutation. Seems PHPDBG needs to be obsoleted.

**Comment by maks-rafalko** [comment]
As we discussed on Slack with you and Jakub Zalas, let's better to force using `pcov` as `phpdbg` seems to have very weird bugs that we had previously and are experiencing now.

I've added a couple of word here https://github.com/jakzal/phpqa/issues/183 to push it forward.

And, since in your particular case you can skip using `phpdbg` because of provided coverage, let's close this issue.

**Comment by sanmai** [comment]
If you’re using @runTestsInSeparateProcesses or @runInSeparateProcess there’s a know PHPDBG related compatibility issue for PHPUnit.
