### ISSUE TITLE
[RFC] Remove debug file log

### ISSUE THREAD

**Issue by theofidry** [infection/infection#1123]
I'm having trouble to understand what values the file log has: it appears to have much less informations than the text one.

Should we remove it?

**Comment by maks-rafalko** [comment]
It's only for testing purposes, is not a replacement, not an alternative for `text` logger. It's removed from documentation and used in many e2e tests:

```
Total: 8
Killed mutants:
===============


Mutator: PublicVisibility
Line 7

Mutator: Plus
Line 9

Mutator: TrueValue
Line 12

Mutator: PublicVisibility
Line 12

Mutator: FalseValue
Line 14

Mutator: NotIdentical
Line 14

Mutator: TrueValue
Line 15

Errors mutants:
===============


Escaped mutants:
================


Timed Out mutants:
==================


Not Covered mutants:
====================


Mutator: FalseValue
Line 17

```

Why do we need to remove it?

This logger is better that `text` logger because it does not work with FS paths and thus always the same regardles of where e2e test is executed.

**Comment by theofidry** [comment]
>Why do we need to remove it?

We don't need to: I'm just asking if it's used and what it's used for, and if not used should be removed :)

Ok I'll update it with a comment in the code then
