### ISSUE TITLE
Add infection to PHIVE (PHAR Installation and Verification Environment)

### ISSUE THREAD

**Issue by shochdoerfer** [infection/infection#134]
I'd love to be able to install infection via [PHIVE](https://phar.io). Steps needed to enable PHIVE support:
1. Deploy a phive.xml file to your webserver, see [here](https://github.com/phar-io/phar.io/blob/master/data/repository.xsd) for the XSD or [here](https://github.com/sebastianbergmann/phar-site-generator) for a project generating such a file
2. Add the phive.xml url to list of [PHIVE repositories](https://github.com/phar-io/phar.io/blob/master/data/repositories.xml)

**Comment by theofidry** [comment]
You can already do it by doing `phive install infection/infection`. Registering a `phive.xml` to the PHIVE repositories is for aliases only :)

It could be nice to have the `infection` alias though to only do `phive install infection`

**Comment by shochdoerfer** [comment]
I was actually referring to the aliases, sorry for making this not clear in the issue description.

**Comment by pxgamer** [comment]
Interesting, when I try installing through Phive it fails to find a `.asc` or `.sig` file.

**Comment by sidz** [comment]
@borNfreee will we add infection to PHIVE?

**Comment by borNfreee** [comment]
Yes, we will. As I understand [from this tutorial](https://phar.io/howto/sign-and-upload-to-github.html), we need to upload `.asc` file to make it compatible with GitHub releases.

I don't want to do it manually each time I release infection, cause we need also to generate `infection.phar.pubkey` using open ssl private key and this GPG `.asc` file. I would like to automate all this process, but currently I'm out of time.

We will do it later with automating the whole process, involving Travis API to store private keys.

**Comment by theofidry** [comment]
@borNfreee when you'll want to tackle this you can follow the [article that I wrote](https://medium.com/@tfidry/create-and-deploy-secure-phars-c5572f10b4dd) detailing how to automate it (this is what I used for PHP-Scoper). There's also a link on how to deal with GPG signatures instead of OpenSSL

**Comment by djmattyg007** [comment]
Is there anything that can be done to help this process?

**Comment by borNfreee** [comment]
> Is there anything that can be done to help this process?

That's not a priority one, at least for me. If you guys want to speed this process up, you can start helping with the whole build process, that I described in [this comment](https://github.com/infection/infection/issues/134#issuecomment-364693747)

It requires too much work, as we still don't have an automated process of building PHARs in our CI. Moreover, we should integrate PHP-Scoper and humbug/Box to build prefixed PHAR for our releases.

So, if you want to help, the first step would be integration PHP-Scoper to our build process (related information here: https://github.com/infection/infection/pull/67#issue-150947973.

**Comment by theofidry** [comment]
Also don't miss https://github.com/infection/infection/pull/67#issuecomment-368300131, there's some work that has already been done :)

**Comment by kalessil** [comment]
+1 from me - phive support is needed.

**Comment by borNfreee** [comment]
I am completely missing the point of having GPG signing instead of our current OpenSSL, because:

1. when you bundling the PHAR with the code and sign it using OpenSSL, it automatically checks whether the content of the PHAR file is the same as it was signed with private key. PHAR in this case automatically search for `phar.pubkey` and fails if it does not exists or do not corresponds to private key

it means when you run `infection.phar` and no `infection.phar.pubkey` exists, you get

```
PHP Fatal error:  Uncaught PharException: phar "infection.phar" openssl signature could not be verified: openssl public key could not be read in infection.phar:9
Stack trace: ...
```

2. when you signing `infection.phar` with GPG key (this is what Phive requires), you get exported key like `infection.phar.asc`, BUT

* if you remove it, you can still run `infection.phar` without any error (no validation at the runtime)
* in order to verify that `infection.phar` has not been changed, you need to run `gpg --verify infection.phar.asc infection.phar`

IMO, this is much worse scenario because

* no runtime validation is happening
* you must have GPG installed on your system

-----

@infection/core and everyone interested in Phive - any thought on this? 

@theseer it would be great if you find some time to wrine an input.

**Comment by theseer** [comment]
Hi,

thanks for the ping :)
Let's see if I can make our case...

## OpenSSL Signatures

Imho, OpenSSL signatures in this context are plain useless since a signature does not provide any identify information. Since the signer is not verifiable anybody could create a garbled phar with a matching pubkey file and you wouldn't notice the difference from an official untampered distribution in terms of runtime validation. Sure, said runtime validation ensures the signature matches the phar file but that's obviously useless.

Worse, the fact you have to have the pubkey next to it with a matching name messes with symlinks and managment tools while not providing actual security.

The latter could easily be avoided if the signature would become part of the phar file rather than being dragged around independently but that's not how things are. And that would still leave the first problem of course.

I could also simply replace the phar file with one that does not include the signature at all and PHP wouldn't complain. Useless.

## GnuPG

Granted, GPG does not provide any runtime validation. But that's no worse than with openssl's pseudo-security with anonymous signatures or for any other binary that you may run unless you hook into the kernel and have an UEFI security layer with keys stored in the UEFI Key safe.

And yes, you do have to have GPG installed to verify GPG signatures. But *every* Linux distribution at least I know of use GPG signatures for packages and/or repository validation. Git also uses GPG for signing commits and tags. So it's extremely unlikely that a target audience user does _not_ have GPG installed on their system. And even if: They could simply skip the checks.

GPG has personalized private keys. So while I can of course tamper with a phar before installation it's unlikely that I'll be able to create a valid signature based on the private key of the official distributor. With that, the installation is secured and the integrity can be verified.

Once the file is on the user's system, the file is in enemy territory and if file permissions allow, anything can be done to it.



Does that make sense?

**Comment by sanmai** [comment]
As far as I understand how Phive works, they need to verify that the package actually comes from the creator, not just that the package wasn't altered. GPG is the best tool for this job. 

So best case for us is to sign the package both with OpenSSL and GPG.

**Comment by theofidry** [comment]
Signing the PHAR with OpenSSL/GPG with the PHAR signing feature has little
value IMO. It is a PITA to manage and is effectively useless after the
first run. Indeed if the PHAR executes the code, the loaded code could
alter the PHAR being used including the signature check.

**Comment by theofidry** [comment]
Just for clarity I’m arguing against the PHAR built in signing feature not
signing the PHAR with GPG like requires by Phive

**Comment by sanmai** [comment]
Well, I'm not a big fan of the PHAR built-in signing feature either. So the questions is if we should ditch that feature and use GPG signing instead to deploy Infection on Phive, am I right?

**Comment by borNfreee** [comment]
> anybody could create a garbled phar with a matching pubkey file and you wouldn't notice the difference from an official untampered distribution in terms of runtime validation

I would like to understand the whole process here. Are you saying the user downloads `phar` and `pubkey`, during downloading both files are replaced by attacker and now new `phar*` matches with new `pubkey*`, so runtime validation still works but this is a completely different PHAR code?

How is that possible? The only one source of PHAR files is Github Releases page (https) for Infection.

> Well, I'm not a big fan of the PHAR built-in signing feature either

What is the technical argument behind this statement?

> So the questions is if we should ditch that feature and use GPG signing instead to deploy Infection on Phive, am I right?

Yes, this is the main questions. 

By the way, trying to verify Phive PHAR, following the steps from [documentation](https://phar.io/):

```bash
[...]

gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79

// output
gpg: keyserver receive failed: No keyserver available

gpg --verify phive.phar.asc phive.phar

// output
gpg: Signature made Tue Jun 26 17:59:24 2018 +03
gpg:                using RSA key 6AF725270AB81E04D79442549D8A98B29B2D5D79
gpg:                issuer "team@phar.io"
gpg: Can't check signature: No public key
```

**Comment by sanmai** [comment]
An attacker can make their own `infection.phar` signed with their own key, and you wouldn't know it. Not just now know it, but almost no way easy way to learn that. Not very secure, I must say. [And this issue.](https://blog.sucuri.net/2017/07/code-injection-in-phar-signed-php-archives.html)

No such thing is possible with GPG signing. You can see exactly who signed that build, and GPG will warn you if a public key is unknown. Just like it does above due some documentation issue (try `gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79` instead).

Other than that there's a non-technical argument, it is just an inconvenience to drag around two files instead of one.

**Comment by theseer** [comment]
>>    anybody could create a garbled phar with a matching pubkey file and you wouldn't notice the difference from an official untampered distribution in terms of runtime validation

> I would like to understand the whole process here. Are you saying the user downloads phar and pubkey, during downloading both files are replaced by attacker and now new phar* matches with new pubkey*, so runtime validation still works but this is a completely different PHAR code?

> How is that possible? The only one source of PHAR files is Github Releases page (https) for Infection.

The original statement regarding security of openssl signatures was that it would allow for a *runtime validation* of the phar. And while that is technically correct, from a security perspective the validation itself is useless as it only verifies that _a_ signature matches the given phar. Given that such a signature can be created by anyone and thus will match a modified phar, this check doesn't add anything to the overall security.

OpenSSL signatures as implemented in `ext/phar` do not provide a means to ensure the signer. For that to work, we'd need to have a CA-setup with certificates rather than just private and public keys. While that could of course be potentially interesting to implement, this is a whole different beast.


Of course modifying the phar in flight during https encrypted transfers is a quite unlikely scenario (- yet not fully impossible). The main concern is not that the file gets corrupted during transfer though but that the attached file was garbled to begin with. From github's point of view, the phar is just some random file that's being attached and hosted on their servers as part of a release. Github has know knowledge of what's inside and there various 3rd party services that can attach files to a release - like for instance travis ci can add a build artifact. 

All that means that while (even though you don't) could sign a commit and/or tag, the file is unknown trust level. Adding a GPG signature to that file fixes that.
And phive uses that signature to ensure only phar's signed of by a known signer get installed.

**Comment by theseer** [comment]
> An attacker can make their own infection.phar signed with their own key, and you wouldn't know it. Not just now know it, but almost no way easy way to learn that. Not very secure, I must say. And this issue.

Hence me saying OpenSSL signatures are useless here.


> No such thing is possible with GPG signing. You can see exactly who signed that build, and GPG will warn you if a public key is unknown. Just like it does above due some documentation issue (try gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79 instead).

Interesting that stopped working. I literally copy pasted my shell calls to the documentation page. I'll update the docs. Thanks for the pointer :)

> Other than that there's a non-technical argument, it is just an inconvenience to drag around two files instead of one.

ACK.

**Comment by borNfreee** [comment]
thanks, now it's more clear.

> The main concern is not that the file gets corrupted during transfer though but that the attached file was garbled to begin with. 

How does Phive solve this issue? As I understand, it just downloads 2 files (`infection.phar` and `infection.phar.asc`) from Github Releases page and executes `gpg --verify infection.phar.asc infection.phar`. So, if the attacker managed to replace files in the release page, GPG can't save us as well. Is it correct or did I miss something?

I think it would be very useful to have FAQ/blog post on the phar.io website with a detailed explanation and comparison GPG vs %other built in signatures in PHAR% other questions we discussed above.

**Comment by theseer** [comment]
Short answer: We don't, since it's a non-issue.

For the verification process to work (e.g. the `gpg --verify ....`), the public part of the private key used for signing must be known on the system doing the verification. That's why we do the import of the public key via it's ID (`gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79` for our signing key for example). Once the public key is in the so called keyring, signatures "linked" to that key can be verified. Otherwise it would be identical to openssl signatures. But as we do not only want to verify it has not been tampered with since it had been signed but also it was signed by someone (read: with a key) we trust, this step is required.

As long as you don't loose your gpg private key, it's close to impossible that anybody else but you can create a signature that can be linked back to that very key. If the attacker uses a different private key however, the verification will fail. An attacker of course could create a new key pair claiming it's you. That's where the key ID and fingerprints comes into play as those cannot be forged. (Well, it probably could but that's what pretty much all cryptography is based on these days so I guess it's reliable enough ;) )

Long story short: Of course the phar and signature could be forged but the signer would not match up with the official signing key and thus the verification would fail. Phive actually warns if a signing key changed and asks you to double check whether that is correct.

That leaves only one problem: On the first install of a phar theoretically the a forged key could be used and we wouldn't notice since we don't know and have no means detect it.  That's why upcomings versions of phive (or the repositories.xml downloaded from phar.io with the alias list to be exact) will have known/trusted IDs and public key data available so we can block this vector at least for the aliased phars. For everybody else you'd have to manually verify if the finger print shown by phive matches the one you expect - for instance by comparing it with the fingerprint published by the project. At Phar.io for examples we publish the fingerprint in the footer of the website to have an independent means of transport.

Regarding an FAQ: Awesome idea. I'll try to make that happen upcoming weekend.

**Comment by borNfreee** [comment]
> That's why upcomings versions of phive (or the repositories.xml downloaded from phar.io with the alias list to be exact) will have known/trusted IDs and public key data available so we can block this vector at least for the aliased phars. 

Tha's what I had in mind when asked previous question. Great!

Thank you for the detailed answers, they helped a lot.

To sum up we will

1. Sign `infection.phar` with GPG and upload it with `infection.phar.asc` to Github Releases
2. Remove OpenSSL algorithm from [Box config](https://github.com/infection/infection/blob/master/box.json.dist#L5)
3. Open PR to add an alias for Infection [here](https://github.com/phar-io/phar.io/blob/master/data/repositories.xml)
4. Add fingerprint to the readme and documentation site
5. And one day, this `repositories.xml` will have an ID as discussed above

**Comment by borNfreee** [comment]
PR for alias https://github.com/phar-io/phar.io/pull/49

**Comment by theseer** [comment]
Merged.

```bash
theseer@nyda /tmp/xx $ phive install infection
Phive 0.11.0-34-gbcf85f7 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/infection/infection/releases
Downloading https://github.com/infection/infection/releases/download/0.10.0-beta.4/infection.phar
Downloading https://github.com/infection/infection/releases/download/0.10.0-beta.4/infection.phar.asc
Downloading key C5095986493B4AA0
Trying hkps.pool.sks-keyservers.net (68.187.0.77)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0xC5095986493B4AA0&op=index&options=mr
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0xC5095986493B4AA0&op=get&options=mr
Successfully downloaded key

	Fingerprint: C6D7 6C32 9EBA DE2F B9C4 58CF C509 5986 493B 4AA0

	Infection PHP <maks.rafalko@gmail.com> (2018-08-05)

	Created: 2018-08-05

Import this key? [y|N] y
Linking /home/theseer/.phive/phars/infection.phar to /tmp/xx/tools/infection

theseer@nyda /tmp/xx $ ./tools/infection --version
You are running Infection with xdebug enabled.
    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____ 
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/
 
Infection - PHP Mutation Testing Framework 0.10.0-beta.4
```
