### ISSUE TITLE
Restart with xdebug

### ISSUE THREAD

**Issue by theofidry** [infection/infection#137]
When we start infection without xdebug and phpdbg, you get:

```
You need to use phpdbg or install and enable xdebug in order to allow for code coverage generation.
```

1) I think the message could receive some pretty formatting with `SymfonyStyle::error()` to make it easier to read.

2) Enabling xdebug is usually easy or at least people are familiar with it. For phpdbg however people are likely not so I think adding the command on how to run it with phpdbg would be more user-friendly (even though it's already in the docs)

3) Which was actually the reason why I wanted to open this issue: as when xdebug is enabled we disable it later on for perf improvements, WDYT of enabling it if neither phpdbg is found and xdebug enabled instead of the error message above? We could then add an information "running with xdebug blabla" when running infection. If the user is not happy with it he can always cancel it and restart with phpdbg.

IMO that would likely be a smoother usage with Infection. I for one often enable/disable (it's dead easy with my shortcuts) for several reasons (perf, actual tests, etc.) so doing that would just works all the time instead.

thoughts?

**Comment by sidz** [comment]
@theofidry here is my thoughts:

1. We can do this 👍 
2. The main reason why we chose this way: 
We can't guaranty that user has (installed) `xdebug` and can't even check if it was installed or not. Two potential cases here:
- extension was installed before but right now it's disabled. This situation is fine and we can enable xdebug on fly.
- extension is not installed. We can't check this on fly and with this situation if we will enable `xdebug.ini` on fly we will get error message (don't remember full message but there will be smth like "Can not load extension blablabla...") from PHP side and it will break infection at all.
Also instead of tell user that he doesn't have `xdebug` it will work while we will need to execute code coverage process.

This doesn't have any affect on `phpdbg` as to use it user will need to execute different command (`phpdbg -qr` instead `php bin/infection`).

3. this thought is good but we can't guaranty that xdebug installed.

**Comment by theofidry** [comment]
Regarding 3 I think that’s fine as long Asnières we bail out with a IX
friendly’ message

**Comment by borNfreee** [comment]
> Regarding 3 I think that’s fine as long Asnières we bail out with a IX
> friendly’ message

could you please clarify what does it mean?

**Comment by theofidry** [comment]
Sorry too much autocorrect from the phone and no double check :P
