### ISSUE TITLE
Reduce coverage runs when using `forceCoversAnnotation="true"` + `--diff-git-filter`?

### ISSUE THREAD

**Issue by Ocramius** [infection/infection#1451]
While talking with a team that uses `--diff-git-filter` and `forceCoversAnnotation="true"` on their codebase, we realized that runtime can be further slimmed down by intersecting `--diff-git-filter` results with the respective `@covers` annotations and respective tests.

In doing so, mutation suite runs that require full test suite coverage right now could run against just a couple changed files, at a massive reduction of wasted CPU/Memory/IO time.

This could also probably be done through a plugin system, which (sorry, my bad) is mostly waiting for my feedback.

**Comment by sanmai** [comment]
How does `forceCoversAnnotation="true"` play here?

I see that we can include only changed files while generating the coverage report:
```xml
    <coverage>
        <include includeUncoveredFilesInCodeCoverageReport="false">
            <file>src/File/Changed/InTheCommit.php</file>
            <file>src/File/Changed/InAnotherCommit.php</file>
        </include>
    </coverage>
```
But we might have it pre-generated for us, and then there's no benefit.

**Comment by Ocramius** [comment]
This could play out as following:

 1. we know that `Foo.php` and `Bar.php` were modified
 2. we know that `FooTest.php` has `/** @covers Foo */`
 3. we know that `BarTest.php` does **NOT EXIST** or **DOES NOT HAVE** `/** @covers Bar */`
 4. we can now decide to run only `FooTest.php` when generating coverage

**Comment by theofidry** [comment]
@Ocramius if `BarTest` does not exists then `Bar` is not covered in which case it could be skipped with `--only-covered`. The PHPUnit annotation is only for forcing the end-user to apply them but it might be:

- Wrong to force it on our side: e.g. someone using the PHPUnit bridge with its automatic @covers
- Someone not interested in relying on the coverage report for running the mutations

So whilst I definitely encourage the `forceCoversAnnotation` usage, especially since there is a PHP-CS-Fixer rule to add `@coversNothing` if no `@covers` is found, I think forcing it via Infection might be too disrupting and opinionated

**Comment by Ocramius** [comment]
No enforcement: just upfront filtering when it is already enforced by config

**Comment by theofidry** [comment]
Oh you mean skipping the executing of the tests that don't have coverage information in the initial test run?

**Comment by Ocramius** [comment]
Correcto: we just use the additional information about the test suite config to reduce execution scope as much as possible.

No change for the end-user.

This ticket is just tracking this possibility though, since I believe this could be feasible by plugins, without landing in core.

**Comment by maks-rafalko** [comment]
See initial implementation and example of usage for PHP-CS-Fixer here: https://github.com/infection/infection/pull/1919
