### ISSUE TITLE
Add support for Pest testing framework

### ISSUE THREAD

**Issue by olivernybroe** [infection/infection#1476]
PestPHP is a testing framework inspired by JEST. 

It uses PhpUnit underneath, so it should be relatively straightforward to support.

An issue has been created in Pest for this, however looking at the discussion it also seems like infection prefers the package to be under their organisation. https://github.com/pestphp/pest/issues/4

## Problems
Some major issues for supporting Pest without any changes in pest, is that the [`TestFrameworkConfigLocator`](https://github.com/infection/infection/blob/master/src/TestFramework/Config/TestFrameworkConfigLocator.php#L73) is determining based on the config name.

However Pest is build on PhpUnit, so their config file is actually also just named `phpunit.xml`. (This can be solved in Pest by Pest allowing a config file named `pest.xml` and then infection would only work if you rename your config file.

**Comment by olivernybroe** [comment]
@owenvoke do you still have the adapter you created where you got infection php working?

**Comment by maks-rafalko** [comment]
I started working on Pest integration on top of PHPUnit adapter at that point in time.

There was a blocker in Pest though - https://github.com/pestphp/pest/issues/48.

Seems like I had some progress with that issue - https://github.com/pestphp/pest/issues/48#issuecomment-639115133 - but it still requires more work, probably from someone who is familiar with Pest, as currently Junit report doesn't work as expected, but Infection requires it.

After this issue is resolved, I can continue work on creating an adapter

**Comment by olivernybroe** [comment]
@maks-rafalko Ah awesome. 

Does infection only support reading Junit reports? Because Pest does have a TeamCity printer where those issues has been fixed. 

However if it does not, then I might be able to look into that and fix the Junit report also.

**Comment by maks-rafalko** [comment]
[Infection requires](https://infection.github.io/guide/command-line-options.html#coverage) both `xml` and `junit` reports to work properly and fast.

So, it does not work with `TeamCity` format.

**Comment by maks-rafalko** [comment]
implemented and released with 0.23.0
