### ISSUE TITLE
CastString mutator should take method return type into account

### ISSUE THREAD

**Issue by shochdoerfer** [infection/infection#1478]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.20.2
| Test Framework version | PHPUnit 9.5.1
| PHP version | PHP 7.4.14
| Platform    | Ubuntu 20.04

I have the following method in my code:
```
protected function getConfig(string $setting): string
{
    // some processing is done here and an array of strings is returned
	$output = [];
	return (string) key($output);
}
```

Infection applied the CastString mutator to get rid of the string typecast for the return value. Since I do not have a test case for the method, Infection reported a not covered mutant which is true.
I am wondering if this is needed because the method has a safeguard in form of the return type hint. Could Infection take that into account and not apply the CastString mutator then dealing with return types?

Not sure if this counts as a bug report or a feature request :)

**Comment by maks-rafalko** [comment]
I assume that the type of `key($output)` is not `string` but something else, right?

So, we have the following:

* if `key($output)` is of type `string`, then casting is redundant and should be removed. Infection clearly shows it
* if `key($output)` is of any other type but not `string`, then this mutant should be killed because we have a type mismatch

From the first look, I don't see that Infection doing something incorrectly here, because Infection doesn't know the type of `key($output)`.

Btw, if you are not interested in mutations generated for not covered code, probably it makes sense to use `--only-covered` option.

**Comment by shochdoerfer** [comment]
Well, I could blame phpstan for telling me to add the typecast but that's a different story :) I already ignored the method in the Infection configuration, that's fine for me.

I was just wondering - and that was the main reason for opening this issue - if Infection does understand the current scope and can make decisions based on the scope. Like in this case the method has a return type hint, thus using the casting mutator is not necessarily needed. That way fewer mutations would get generated and Infection could run faster.

**Comment by maks-rafalko** [comment]
> Infection does understand the current scope and can make decisions based on the scope.

* Infection **can** understand return type of the method
* Infection can **not** understand types of variables/expressions. So it doesn't know the type of `key($output)`. That's why it tries to remove `(string)` casting, checking if it makes sense to have `(string)` here. If `(string)` is removed and tests are green, it means the type of `key($output)` is `string` and cast operator is redundant, thus should be removed

I would say that Infection should skip such mutation only if it 100% sure, that the type of expression is not `(string)`. In this case it will lead to always killed mutant, which is a waste of resources.

**Comment by shochdoerfer** [comment]
Got it. Makes sense. Thanks for the insights.
