### ISSUE TITLE
No line of code was executed during tests.

### ISSUE THREAD

**Issue by alexdodonov** [infection/infection#1542]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.21.5
| Test Framework version | PHPUnit 8.5.19
| PHP version | 7.4.4
| Platform    | Windows
| Github Repo | https://github.com/alexdodonov/mezon-router

Hi! I am getting error "No line of code was executed during tests. This could be due to `@covers` annotations or your  
  PHPUnit filters not being set up correctly."

Here is infection config:
```json
{
	"source": {
		"directories": [
			"./Mezon/Router"
		],
		"excludes": [
			"./Mezon/Router/Tests"
		]
	},
	"phpUnit": {
		"customPath": ".\/vendor\/phpunit\/phpunit\/phpunit"
	},
	"logs": {
		"text": ".\/tmp\/infection.txt"
	},
	"mutators": {
		"@default": true
	}
}
```

Here is PHPUnit config:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/7.0/phpunit.xsd"
	backupGlobals="false" colors="true" bootstrap='./vendor/autoload.php'
	stopOnError="true" stopOnFailure="true">
	<php>
		<ini name="error_reporting" value="-1" />
	</php>

	<testsuites>
		<testsuite name="unit">
			<directory suffix="UnitTest.php">
				./Mezon/Router/Tests
			</directory>
		</testsuite>
	</testsuites>

	<filter>
		<whitelist>
			<directory>./Mezon/Router</directory>
			<exclude>
				<directory suffix="UnitTest.php">
					./Mezon/Router/Tests
				</directory>
				<directory>./vendor</directory>
				<file>autoload.php</file>
			</exclude>
		</whitelist>
	</filter>

	<logging>
		<log type="coverage-html"
			target="./tmp/coverage-phpunit.html"></log>
		<log type="coverage-text" target="php://stdout"
			showOnlySummary="true"></log>
	</logging>
</phpunit>
``` 

What do I do wrong?

**Comment by sanmai** [comment]
Try running it with `XDEBUG_MODE=coverage`

**Comment by alexdodonov** [comment]
It have not helped (

**Comment by maks-rafalko** [comment]
Thank you very much for providing a repository with reproducible issue, this is how the bug report should look like!

I was able to reproduce it and the reason of this bug is quite interesting. Your `phpunit.xml` file contains `\n\t` around the relative paths, and when Infection tries to replace relative paths with absolute ones - it builds incorrect paths with `\n\t` inside, see

![tabs-bug](https://user-images.githubusercontent.com/3725595/128754099-79fbb213-ed66-42d2-aa63-87e0e2b35050.png)

https://github.com/infection/infection/pull/1550 fixes the issue.

While you are waiting for the new release, you can fix this issue just by updating your `phpunit.xml` like this:

![tabs-bug-workaround](https://user-images.githubusercontent.com/3725595/128754179-c578eb22-819b-404a-9f81-f1a5a9d44a81.png)
