### ISSUE TITLE
Mutants are modifying my files because of tests

### ISSUE THREAD

**Issue by VincentLanglet** [infection/infection#1556]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.24.0
| Test Framework version | PHPUnit 9.5.0
| PHP version | 7.4
| Platform    | MacOS
| Github Repo | https://github.com/VincentLanglet/Twig-CS-Fixer

After running infection, I end up with two files 
- tests/Runner/Fixtures/file.twig
- tests/Sniff/EmptyLines/EmptyLinesTest.twig
modified. And if I run the PHPUnit tests again, they don't pass anymore.

I run a "fixer" on the file ` tests/Runner/Fixtures/file.twig`, my test is supposed to  expect an exception. I assume one mutant has no exception, the file is "fixed", and then the tests keeps running with this new file.

I run a "linter" on the file `tests/Sniff/EmptyLines/EmptyLinesTest.twig`, it's not supposed to be modified. I assume one mutant is changing the boolean option `fix` from false to true, and it's fixed ; then the tests keeps running with this new file.

Does it means that tests are not always running on the same files and I end up with false negative ?

Would it be possible to revert the changes made to tests files after each tests ?

**Comment by maks-rafalko** [comment]
Hi, in Mutation Testing (be it Infection or other lib), tests files should never be modified, you should exclude tests folder in `infection.json`.

For source files that need to be modified, Infection creates Mutants (original file plus 1 mutation) in a `/tmp` folder by default, so that original source code files are never modified as well.

If infection changes `fix` from false to true, please ignore this file from mutating process altogether, or just this method or line, see https://infection.github.io/guide/how-to.html#How-to-disable-Mutators-and-profiles
