### ISSUE TITLE
Phar or not Phar?

### ISSUE THREAD

**Issue by niconoe-** [infection/infection#1565]
Hi all!

I just have a question regarding the releases here: https://github.com/infection/infection/releases.

Sometimes, there are phar files in assets, (0.24, 0.23, ...) but sometimes there's not (0.25, 0.22, ...).

What is the rule about it? I'm asking as I'm creating a Dockerfile downloading this phar to use Infection in several projects though different versions, but if the phar is missing, of course I can't rely on it.

I don't mind of always having a phar or never have it, I just need to have somethng to trust to build my Dockerfile images actually, so I need some consistent process and being in this situation is not consistent.

Thanks a lot!
Have a nice day!

**Comment by maks-rafalko** [comment]
Hello, thanks for your question and concerns, totally makes sense. Right now we have an issue with generating PHAR file, this is what I'm going to fix, but with limited time and resources.

This happened because of https://github.com/infection/infection/issues/1508, and once we add generating and testing PHAR back to our pipeline, I think we will be sure that every release will have attached file immediately, without a delay.

For 0.25, I will deploy the PHAR as soon as the issue is fixed. Sorry about that.

**Comment by maks-rafalko** [comment]
Uploaded PHAR files

Please report any issues, thank you.

**Comment by niconoe-** [comment]
Ok, thank you very much for your answer and for taking the time to upload the PHAR as well, it will definitly help me for the version 0.25.0.

I hope you'll find some help regarding #1508 as it looks like really hard to fix, since because of GitHub Actions not performing E2E test, you're blocked, if I understand correctly.

I'll give you feedback about how 0.25.0 is working with the PHAR in few hours, when I'll get back to work.

Thanks again.
Regards,

**Comment by niconoe-** [comment]
0.25.0 tested and working like a charm! Thanks a lot!
