### ISSUE TITLE
Paratest compatibility

### ISSUE THREAD

**Issue by Back1ng** [infection/infection#1692]
When trying to use multi-threaded testing, the use with the database does not work as it should. When running a test, migrations are performed, but duplicates are detected, causing tests to crash and mutants to be considered killed.

To fix this problem, I think need to add paratest to the supported test frameworks. I speak from experience using Laravel framework. Now you can't get them together and have to run the mutations in the same thread.

[Laravel. Parallel tests.](https://laravel.com/docs/master/testing#running-tests-in-parallel)
[paratestphp/paratest](https://github.com/paratestphp/paratest)

**Comment by sanmai** [comment]
See: https://infection.github.io/guide/how-to.html#How-to-run-Infection-for-functional-tests

**Comment by maks-rafalko** [comment]
In addition to what @sanmai already provided:

* we tried to support Paratest out of the box, but this works surprisingly slower than PHPUnit, see a detailed explanation https://github.com/infection/infection/pull/1552
* if your tests work correctly with Paratest and its `TEST_TOKEN` - Infection will work correctly as well, because it also populates `TEST_TOKEN` under the hood, so tests processes will use different databases in your case

**Comment by maks-rafalko** [comment]
1. Could you please show the full command line how you run your tests?
2. Could you please show the full command line how you run Infection?
3. Do you use different databases for multithreaded testing? In other words, do you use `TEST_TOKEN` that paratest provides?

I'm trying to understand what works correctly with your tests suite and why Infection doesn't work (when it should).

**Comment by sanmai** [comment]
> At this point, I don't see a solution without digging deeper into the source code.

This is a good idea most of the time. Best of luck!
