### ISSUE TITLE
Restore code/file/folder after running mutations

### ISSUE THREAD

**Issue by VincentLanglet** [infection/infection#1746]
**Is your feature request related to a problem? Please describe.**
I have a library which is 
- reading some files (file_get_content)
- creating/writing some files (file_put_content)
- changing permissions of some files (chmod)

I have written test about all my method, and committed multiple tests files, the issue is that as soon as I run mutations locally, because of mutations, I end up with
- Some new files created which are not created when running the tests normally
- Some permissions modified

**Describe the solution you'd like**
In a dream world, I would like infection to do a snapshot of the working directory before running the test with mutations.
Then, after running mutations I would like infection to restore the code/files/etc like it was in the snapshot.

Is it doable ?

**Comment by sanmai** [comment]
I guess Infection could leverage Docker is some way to create a layer for each mutation, discarding it afterwards.

**Comment by maks-rafalko** [comment]
To be honest I didn't get the issue, could you please provide an example? Do you have test files under git that are modified by your tests? And you are saying Infection "breaks" them?

If yes, IMO your tests cases should copy original files to some `tmp` dir and do all the changes with the files there, removing this folder when testing process is completed. This way Infection will do the same, and original files won't be affected.

From my understanding, changing the files "in a working directory" is not a correct way in the first place.

**Comment by VincentLanglet** [comment]
> To be honest I didn't get the issue, could you please provide an example? Do you have test files under git that are modified by your tests? And you are saying Infection "breaks" them?

It could be the opposite.

Let's say I have a method
```
public function lint(string $filePath, bool $dryRun = true)
{
    // do things
    if (!$dryRun) {
         file_put_contents($filePath, $content);
    }
}
```
And I write a test about this method which call `$this->lint('foo.php')`.
In my test I only checking the output of the method to see, the file is not modified.

But if a mutation is changing the code to
```
public function lint(string $filePath, bool $dryRun = true)
{
    // do things
    if (true) {
         file_put_contents($filePath, $content);
    }
}
```
then the file is modified.

Same could exist for created files.

> From my understanding, changing the files "in a working directory" is not a correct way in the first place.

I agree, but in the previous example, it would require to do the same even if I'm just reading the files in my tests, because the mutation are writing them. I shouldn't (add) code for the mutations.

**Comment by theofidry** [comment]
IMO Infection cannot be aware of all your system constraints and it is something you need to take care of yourself.

Let's take an example with the database: let's say you have a fixture setup, in the test you manipulate the records, and for some reason (test in mid of development still), a record that you did not expect is changed (e.g. a sequence that was incremented and this said sequence wasn't expected to be changed, so the fixture setup does not care of resetting it), which results in the next tests to fail although they could now be correct.

Usually for this reason, there two approaches about those kind of DB tests:

- wrapping any test within transactions which allows for a rollback, regardless of if the test itself was correct or not
- having a more resilient fixture setup (which may leverage snapshots) but ensures the whole DB state is correct initially regardless of what it was before

I would to some degree do the same thing with the FS. It's obviously not nearly as convenient: you can't easily wrap the whole thing in a transaction neither can you snapshot the _whole_ system, it needs to be within a reasonable scope, but you also don't want a mistake to irreversibly break everything (in the sense of running the test again would no longer work).

This is partly why we use this [FilesystemTestCase](https://github.com/infection/infection/blob/master/tests/phpunit/FileSystem/FileSystemTestCase.php), I personally used it long before as well, precisely because running into this issue even without Infection.

Also note that if too expensive, you could also conditionally set this strategy whenever the test is executed by infection (this can be detected via the environment variable).

**Comment by sanmai** [comment]
You can also run Infection in a container, discarding it together with all dangling files after the run.

**Comment by sidz** [comment]
Agree that Infection shouldn't care about this.
