### ISSUE TITLE
Dependency on sebastian/diff

### ISSUE THREAD

**Issue by sergekukharev** [infection/infection#21]
Hi!

Wanted to try out Infection, but could not install it in my environment:
```
composer require infection/infection --dev
```

I know that recommended installation is through PHAR or global composer installation, but I would like to track my dependencies, especially if I'm adding `infection.json.dist` to my project.

The problem is with the `sebastian/diff` package, I got conflicts:
```
- Installation request for infection/infection ^0.5.1 -> satisfiable by infection/infection[0.5.1].
    - Conclusion: remove sebastian/diff 2.0.1
    - Conclusion: don't install sebastian/diff 2.0.1
    - infection/infection 0.5.1 requires sebastian/diff ^1.4 -> satisfiable by sebastian/diff[1.4.0, 1.4.1, 1.4.2, 1.4.3].
    - Can only install one of: sebastian/diff[1.4.0, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.1, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.2, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.3, 2.0.1].
    - Installation request for sebastian/diff (locked at 2.0.1) -> satisfiable by sebastian/diff[2.0.1].
```

`composer why sebastian/diff` hints me that my PHPUnit version (6.3.0) requires sebastian/diff ^2.0.

Let's think together what can be done, cause simply updating to ^2.0 might break older PHPUnit version projects. It's weird how a 3rd package dependency makes your project dependent on specific PHPUnit version.

**Comment by borNfreee** [comment]
Thank you for trying out Infection, Serge.

The problem you are talking about is not so easy. I've investigated it a bit, and here is what I found:

#### composer-bin-plugin

https://github.com/bamarni/composer-bin-plugin - "No conflicts for your bin dependencies"

This composer plugin allows you to install bin vendors in isolated locations. I recommend to read its description, there are very impressive examples.

This plugin will definitely solve an issue, but you will have to add this plugin as a dependency.

There are several other repositories/libs that try to solve conflicting classes issue:

#### PHPStan (static analyzer):

https://github.com/phpstan/phpstan-shim + https://github.com/fprochazka/phpstan-compiler. Sp they created a different composer package with just one phar `phpstan.phar` file, which has all files' namespaces prefixed in order to avoid conflicts.

In this case you will depend on composer package, but actually will run phar file

```bash
vendor/bin/phpstan.phar analyse src
```

#### PHP Scoper

There is a similar project to prefix namespaces for `phar`: https://github.com/humbug/php-scoper

---------

I think that the best way is to use the first options - composer-bin-plugin. In this case we don't need to have prefixed phars and any project can depend on Infection and it will be perfectly isolated.

Feel free to post your thoughts.

**Comment by theofidry** [comment]
I think the solution on the long-term is to use a PHAR for which the bundled code is isolated. Short term solution I think it's better to have those conflicts and resolve them, if you avoid them with PHARs or tools like composer-bin-plugin, you'll sure no longer have a conflict per se but the code can break without any warning

**Comment by borNfreee** [comment]
I think we have a temporary solution for now and can close the ticket.

Adding PHP-Scoper or any other way of code isolation will be handled in a separate ticket.
