### ISSUE TITLE
Warn users about change to log-verbosity, change it for 0.10.0

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#244]
Currently our highest verbosity is 1, and the lowest verbosity is 3. Which is backwards to how everyone else is doing it.

I suggest to change it to the following:
* 0 -> No logging
* 1 -> Hide killed mutations (default)
* 2 -> Show all mutations

For `0.9.0` Add a notice if the user is using log-verbosity, that tells the end user that it will be changed in the next update.

Extracted from: https://github.com/infection/infection/pull/221#discussion_r174892392

**Comment by sanmai** [comment]
How about if we keep this option unchanged for backward compatibility in terms of numeric arguments, but instead introduce literal arguments. Say:

* `none` for no logging
* `default` to hide killed mutations
* `all` to show everything

This way no warnings will be needed. And we also gain ability to add more logging levels in future.

Handling for numeric arguments will be left in code, but a note about them will be removed from the docs etc.

**Comment by sidz** [comment]
@BackEndTea The main idea of that verbosity order was that we could have more levels (and we've already added a new one) and with your approach you will break compatibility each time when you'll add a new level. For example you'll need to add a new level between 1 and 2.

I totally agree with @sanmai that the best approach in this case would be: use names instead of numbers.
