### ISSUE TITLE
Add HTML logging option

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#340]
**Is your feature request related to a problem? Please describe.**
One of the things i really like about phpunit is the html coverage log. I can easily see what is covered, and what is not. The current infection log may be somewhat daunting to users who haven't used infection before, or may not even make much sense.

Its also difficult to 'perfect' a certain set of classes that you are working on, since its difficult to filter them out.

**Describe the solution you'd like**
I would like to see one or more human readable outputs of infection. My favourite would be a html option, but for starters a markdown version could do a lot for us as well.

Edit: a good reference [the stryker HTML report](https://stryker-mutator.io/stryker-html-reporter/)

**Comment by borNfreee** [comment]
We can think about something like Stryker has

* http://stryker-mutator.io/stryker-html-reporter/
* http://stryker-mutator.io/stryker-html-reporter/child-proxy/ChildProcessProxy.ts.html

probably even reuse their code somehow

**Comment by Spudley** [comment]
I would also like to see HTML reporting option.  +1.

**Comment by cn7r66** [comment]
Hi!

I started writing an HTML logger, It still need some polishing and testing but maybe can be a good starting point.

[Here](https://cn7r66.github.io/report/) you can see a demo of the report. (I've not implemented the file template with source and diffs yet)

If no one is working on this feature i can invest some more time and finish it.

**Comment by borNfreee** [comment]
It looks gorgeous!!!

I'm not aware of anyone working on this feature.

**Comment by cn7r66** [comment]
Great! If so, i will continue.

Meanwhile i've added all the metrics to the table, added file/directory icon near the name, added the legend and started working on the file template.

I've pushed the current state to my github page. (Same link of the previous message)

**Comment by borNfreee** [comment]
Do you have any progress @cn7r66? Your examples look fantastic, would be too bad to lose this work.

**Comment by nicojs** [comment]
Dear friends from the awesome infection PHP community.

🤝 

We have open sourced our HTML reporter as a custom element (using the [web components specifications](https://www.webcomponents.org/specs)). That way, creating an html report is as easy as writing your report to a JSON file and create a small template html file. We needed this internally to support both Stryker4s and Stryker.NET, but decided to make it so other mutation testing frameworks can benefit as well.

Basically: mutation testing implementers need to do the following:

1. Generate a json file based on the mutation-testing json schema: https://github.com/stryker-mutator/mutation-testing-elements/blob/master/packages/mutation-testing-report-schema/src/mutation-testing-report-schema.json
2. Create a simple html file:
   ```html
   <!DOCTYPE html>
   <head>
      <title>Simple example - Mutation test elements</title>
      <script src="https://www.unpkg.com/mutation-testing-elements@1.0.2/dist/mutation-test-elements.js"></script>
   </head>

   <body>
       <mutation-test-report-app title-postfix="InfectionPHP" src="mutation-report.json">
           Your browser does not support custom elements. Please use a modern browser.
       </mutation-test-report-app>
   </body>

   </html>
   ```
   See mutation-testing-elements readme: https://github.com/stryker-mutator/mutation-testing-elements/tree/master/packages/mutation-testing-elements#readme for more information.

@borNfreee The new schema will also be supported by the [stryker dashboard](https://dashboard.stryker-mutator.io) in the future. So you will be able to upload it there so that the dashboard can serve the same html file.

If for any reason the mutation-testing-report-schema does not satisfy your needs, or is impossible to provide, please [open an issue](https://github.com/stryker-mutator/mutation-testing-elements/issues).

I'll also be writing a blog article on this (probably this weekend).

Hope this helps!

**Comment by borNfreee** [comment]
Thank you very much, Nico! 

I just tried it with the [examples](https://github.com/stryker-mutator/mutation-testing-elements/tree/master/packages/mutation-testing-elements/testResources) from your repository and it works really great.

**Comment by maks-rafalko** [comment]
Seems like we can now simply upload a json file with [such schema](https://github.com/stryker-mutator/mutation-testing-elements/blob/76c1b36649640c1606e9f33932507d7ed71b4c9a/packages/mutation-testing-report-schema/src/mutation-testing-report-schema.json) to Stryker Dashboard

See https://github.com/stryker-mutator/stryker-handbook/blob/master/dashboard.md

**Comment by maks-rafalko** [comment]
Implemented https://github.com/infection/infection/pull/1625
