### ISSUE TITLE
[RFC] Run the project test suite with random order

### ISSUE THREAD

**Issue by borNfreee** [infection/infection#396]
Extracted from Slack and originally raised by @BackEndTea

#### Problem

There can be a situation when unit test can implicitly depend on other unit test (by human mistake or any other reason) and changing the order of executed tests leads to fail. 

Infection runs only several unit tests for each Mutant, with the order of execution time (fastest - first), so if the tests fails because of incorrect (not original) order, we have a killed Mutant which is obviously not correct.

#### Proposal

We can run unit tests in a random order during our "Run initial test suite" stage in Infection. By doing it, we can check that each test is independent and if the test suite fails with random order, we can notify user about this issue with a detailed error message.

Since PHPUnit 7.2, we can do it out of the box ([related PR](https://github.com/sebastianbergmann/phpunit/pull/3092), [documentation](https://github.com/epdenouden/phpunit/wiki/PHPUnit-test-running-order-management))

What do you think about adding this feature?

**Comment by BackEndTea** [comment]
👍 As long as its properly documented.

For its implementation i'd do the following

Checks (in order)
* PHPUnit  7.3 or higher, use `--order-by=random` flag
* PHPUnit 7.2 use the `--random-order` flag, which is deprecated in 7.3
* Otherwise: check if `fiunchinho/phpunit-randomizer` is installed, and run that
* Run normal order

Or, we could create our own version of this so we can always run in random order. This does mean that we have to work with actual phpunit code, instead of just its cli. Meaning we will have more issues in supporting different versions.

I'm not sure if this is possible or relevant for phpspec.

**Comment by sanmai** [comment]
Great idea! We should do it, but not without a proper explanation for a user.

**Comment by deleugpn** [comment]
If I understood this correctly, people providing code coverage to infection would skip this feeature and perhaps should be warned about it.
