### ISSUE TITLE
Family of rounding functions mutators

### ISSUE THREAD

**Issue by sanmai** [infection/infection#432]
PR #431 shows that we can't tell if a test is bound to account all rounding errors or not. 

For this job would really help having function call mutators, that would change `floor` to `round`, and `round` to `floor`, to `floor` to `ceil`, `ceil` to `round`, and any other combinations.

E.g. this mutation being caught would mean that tests are really testing that we're rounding down at all times:
```diff
- return floor($this->a / $this->b);
+ return round($this->a / $this->b);
```

Should be very straightforward to make.

**Comment by deleugpn** [comment]
Started working on this today. If nobody comes up with a PR for this, I'll try to open one in the next few days. 
I already learned a little about how the tests and the mutators work, however since there's no example of mutators replacing one `Node\Name\FuncCall` with another, I'm still trying to figure out how PhpParser works.

One thing I might get early feedback though: should there be one mutator for each combination of changes? I'm currently building one `Infection\Mutator\Rounding\Round` that is capable of swapping both `floor` and `ceil` with `round`. That way, the end result is probably 3 new mutators.

**Comment by borNfreee** [comment]
Sorry, missclicked from mobile phone.

> One thing I might get early feedback though: should there be one mutator for each combination of changes?

Oops, I have already started to do it as one mutator that `yield`s many mutations in branch [`yield-mutations`](https://github.com/infection/infection/tree/yield-mutations?files=1) 

I always happy when people contribute to open source, so if you want, you can continue there in that branch, I will push it as soon as I will be at home.

The main idea was not to create N mutators, but create only one, and this will be possible only in that branch. It will be a good example how powerful interface with Generators is.

**Comment by deleugpn** [comment]
Hey @borNfreee I'm not sure I understood what you meant by one mutator. I was thinking that we would have 3 new Mutator classes (Round, Float and Ceil), each one capable of mutating the function call into the other two.
I used the preg_match test case and I noticed it uses Generators for the test code, not sure if that's what you meant. I opened PR https://github.com/infection/infection/pull/447 to help you guide me towards the right path if it makes it easier.
I'm not working on it right now, but I'm expecting to have a couple of hours tomorrow to try and make the mutations work.

**Comment by borNfreee** [comment]
Ok, let me explain it with more details.

I'm working on a new feature that will allow each Mutator produce N mutations instead of just one. It's better to see it with the code example:

instead of this:

```php
# Arithmetic/Plus.php

public function mutate(Node $node)
{
    return new Node\Expr\BinaryOp\Minus($node->left, $node->right, $node->getAttributes());
}
```

we will have this:

```php
# Arithmetic/Plus.php

public function mutate(Node $node): \Generator
{
    yield new Node\Expr\BinaryOp\Minus($node->left, $node->right, $node->getAttributes());
}

```

Note the `\Generator` return type and `yield` keyword instead of `return`. 

#### Why is it needed?

This is needed exactly for mutators like this one (rounding family of mutators), where **one** Mutator can produce **many** mutations instead of creating N separate Mutator classes.

Also, this will allow us to produce as many mutations as we want for one `Node` instance: example here is a mutator that will remove groups from Regular Expression:

```diff
- /several(.*)groups(.*)/
+ /severalgroups(.*)/
+ /several(.*)groups/ 
```

Note that there are 2 mutations from only 1 node (string). This is impossible to do with the current (in master branch) Mutators implementation.

So, today I have created `RoundingFamily` mutator that does just what I described above - it produces 2 mutatorions for one `Node`, in particular:

1. it mutates `floor()` to `ceil()` AND `round()`
2. it mutates  `ceil()` to `floor()` AND `round()`
3. it mutates `round()` to `ceil()` AND `round()`

Look at this commit: https://github.com/infection/infection/commit/850ed16b41174a83c13df7c00c242c0131c9ac36

All this logic is inside one class thanks to `yield`ing many mutations in a `foreach` loop.

That's why in my previous message I suggested to continue your work on `yield-mutations` branch rather tha creating separate classes.

**Comment by deleugpn** [comment]
Thank you so much for all the time to explain. I can see why this new change is quite exciting. One concern though: will the new strategy prevent people from excluding/ignoring a specific mutation without excluding the whole group? Take the Rounding as an example, if we have Round, Floor and Ceil mutators, we get to ignore each separately if necessary, correct? If a single mutator produces all 3, is it a all-or-nothing when ignoring?

Btw, infection is amazing and mutations are very exciting stuff! Thank you for the awesome work.

**Comment by borNfreee** [comment]
> is it a all-or-nothing when ignoring?

Doing this in `infection.json` will ignore all 3 mutations:

```js
{
    [...]
    "mutators": {
        "RoundingFamily": false
    }
}
```

But we can do it smarter:

```js
{
    [...]
    "mutators": {
        "RoundingFamily": {
            "functions": ["ceil", "floor"] // we are ignoring `round` here
        }
    }
}
```

^ this is just an example how it *can* be. We already parse this file and all keys under `RoundingFamily` key [are passed](https://github.com/infection/infection/blob/befd28b1adfb2468f2318010211d7ca5232c2e56/src/Mutator/Util/Mutator.php#L24) to the `Mutator` constructor as `MutatorConfig` object, thus it is trivial to implement on the `RoundingFamily` class level.

So for each Mutator we can have "setting" exactly like PHP-CS-Fixer has settings for each fixer: 

`array_syntax` fixer, settings `syntax ('long', 'short')`
