### ISSUE TITLE
Add json-schema validation for `infection.json.dist` config file

### ISSUE THREAD

**Issue by borNfreee** [infection/infection#451]
Related:

* https://github.com/infection/infection/issues/206
* https://github.com/infection/infection/issues/419

Also https://github.com/infection/infection/issues/204#issuecomment-370335823

> How about providing a JSON Schema and then using [justinrainbow/json-schema](https://github.com/justinrainbow/json-schema) to validate it, after ensuring we actually have valid JSON?

**Comment by sidz** [comment]
As we will implement schema validation for our config file it looks like that it shouldn't be possible to allow Infection to continue processed if the configuration file doesn't exist (like we do currently)

https://github.com/infection/infection/blob/master/src/Console/InfectionContainer.php#L233-L240

this `catch` generates valid empty json which will pass the next condition and then InfectionCommand will trigger `configure` command for case when configuration file doesn't exist

https://github.com/infection/infection/blob/master/src/Command/InfectionCommand.php#L298-L313

Because an empty config file shouldn't be valid for us and at least `source.directories` option should be required (if you thing that we need to add more required fields please give me a nudge) suggest to stop doing this and start think that an empty json is invalid for us.

With this idea it will mean that we should show a message for case when Infection can't find a config file and show a message like psalm, composer do.

An example from psalm:
```
Could not locate a config XML file in path /var/www/infection/. Have you run 'psalm --init' ?
```
Composer:
```
Composer could not find a composer.json file in /var/www/composer
```

thoughts?

**Comment by borNfreee** [comment]
> it shouldn't be possible to allow Infection to continue processed if the configuration file doesn't exist

This is a huge DX feature from my point of view and this is very convinient to run infection for the first time and let it automaticallu run `configure` command for you, and then continue without any other steps.

So, my vote is to save this functionality despite any technical decisions.

We can generate `{"source": {"directories": ["src"]}}` instead of `{}` and tweak it during the `configure` phase by our Guessers, or use Guessers at this point. Does it make sense?

-----

PS shitty permalink-bot, I have uninstalled it because it breaks line numbers in URLs

**Comment by borNfreee** [comment]
implemented
