### ISSUE TITLE
Cli usage guide outdated

### ISSUE THREAD

**Issue by Stratadox** [infection/infection#455]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.10.0
| Test Framework version | N/A
| PHP version | N/A
| Platform    | Travis
| Github Repo | -

Error:
> The command "wget https://github.com/infection/infection/releases/download/0.10.0/infection.phar.pubkey" failed and exited with 8 during .

Steps to reproduce:
- Follow the guide at [infeciton.github.io](https://infection.github.io/guide/using-with-ci.html#Using-with-Travis)
- Replace 0.8.0 with the latest version
- See build fail

Supposedly caused by the repo not using pubkeys any more.

**Comment by BackEndTea** [comment]
It displays the new `.asc` files for me, instead of `.pubkey`. The website has a service-worker, and i think the strategy has a N+1 problem, where it will always display from cache, and then refresh the cache as needed. Which means you will always see the info that was up to date for you previous refresh.

Do you still get the `pubkey` info once you refresh the page?

**Comment by Stratadox** [comment]
Interesting effect: refreshing the page does indeed give new instructions. However, the version number seems stuck at 0.8.0, so after refreshing the page instructs me to use `wget https://github.com/infection/infection/releases/download/0.8.0/infection.phar.asc` which equally produces a 404.

It does seem to solve my particular problem, but it also seems to show a problem with the version number in the website's service-worker.

**Comment by borNfreee** [comment]
I have removed service worker plugin, it should work correctly now.

In the worst case, user will have to remove the cache.
