### ISSUE TITLE
Please implement HTML reporting

### ISSUE THREAD

**Issue by Spudley** [infection/infection#473]
**Is your feature request related to a problem? Please describe.**
I'm very happy with Infection. It is a great addition to my CI process. However, viewing the Infection reports from within my CI tool is not a great experience because the reports are plain text.

**Describe the solution you'd like**
Ideally Infection would be able to product a set of HTML files that I can publish within my CI tool, and which will allow me to navigate through the mutations by file or by mutation type, and show me the code for the mutation along with the results.

I am envisioning this as looking something similar to how phpUnit's code coverage reports look.

**Describe alternatives you've considered**
Right now, I have my CI process publishing the raw log files generated by Infection.

**Additional context**
My CI tool is Jenkins, but I would imagine the same would apply to other tools.

**Comment by borNfreee** [comment]
Thanks for posting this feature request! This makes sense without any doubts.

I mark it as duplicated since we already have it: https://github.com/infection/infection/issues/340

Renamed https://github.com/infection/infection/issues/340 as I think it was hard to find it by `HTML` keyword.

We will keep an eye and see how many users require this format and eventually implement it. You can find examples of how Stryker (mutation testing for JS/TS) does it in the related issue.

Thank you.

**Comment by Spudley** [comment]
Thanks for the response. Happy to close as its a duplicate. I have given 👍 to #340.
