### ISSUE TITLE
Zero percent code coverage is not an issue for Infection

### ISSUE THREAD

**Issue by sanmai** [infection/infection#488]
| Question    | Answer
| ------------| ---------------
| Infection version | master
| Test Framework version | any

As shown in https://github.com/infection/infection/issues/246#issuecomment-423861590 Infection does not hinder at all, and continue as usual even if there's a zero percent coverage. Instead it would make a perfect sense to abruptly stop with an error. This way a user will immediately know they have a problem with code coverage reporting.

For example, in the case of a coverage report below, it makes no sense for Infection to continue since all mutants will be uncovered.
```                         
 Summary:                
  Classes:  0.00% (0/12) 
  Methods:  0.00% (0/27) 
  Lines:    0.00% (0/152)
```
```
Processing source code files: 19/19
Creating mutated files and processes: 147/147
.: killed, M: escaped, S: uncovered, E: fatal error, T: timed out

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   ( 50 / 147)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   (100 / 147)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS      (147 / 147)

147 mutations were generated:
       0 mutants were killed
     147 mutants were not covered by tests
       0 covered mutants were not detected
       0 errors were encountered
       0 time outs were encountered
```
The only case where Infection can continue without an error is when a user explitedly set required minimal MSI to zero. So we could understand that the user knows what they doing.

**Comment by borNfreee** [comment]
It turned out this is more tricky than I thought.

PHPUnit code coverage `xml` report produces several levels of Coverage report, for 

* lines
* methods
* functions
* classes
* traits

Stats block in this `xml` file looke like this:

```xml
<totals>
  <lines total="21" comments="0" code="21" executable="6" executed="2" percent="33.33"/>
  <methods count="1" tested="0" percent="0.00"/>
  <functions count="3" tested="2" percent="66.67"/>
  <classes count="1" tested="0" percent="0.00"/>
  <traits count="0" tested="0" percent="0"/>
</totals>
```

Consider the following cases:

#### 1. No tests at all, absolute `0%` coverages 

```xml
<totals>
  <lines total="21" comments="0" code="21" executable="6" executed="0" percent="0"/>
  <methods count="1" tested="0" percent="0.00"/>
  <functions count="3" tested="0" percent="0"/>
  <classes count="1" tested="0" percent="0.00"/>
  <traits count="0" tested="0" percent="0"/>
</totals>
```

Lines, functions, methods, traits, classes - all have `0%`

✔We can stop Infection execution here.

#### 2. We have tests for global functions

```php
function foo() {
    return function () {
        return 1;
    };
}
```

`xml` report for this code:

```xml
<totals>
  <lines total="21" comments="5" code="16" executable="5" executed="2" percent="40.00"/>
  <methods count="1" tested="0" percent="0.00"/>
  <functions count="2" tested="2" percent="100.00"/>
  <classes count="1" tested="0" percent="0.00"/>
  <traits count="0" tested="0" percent="0"/>
</totals>
```

✔We can stop infection here *because we don't mutate global functions*. Thus, all Mutants will be skipped in any case.

#### 3. We have tests for global functions and for global anonymous functions

```php
function foo() {
    return function () {
        return 1;
    };
}

$squareGlobalFunction = function (int $number): int {
    return $number * $number;
};
```

`xml` report:

```xml
<totals>
  <lines total="21" comments="0" code="21" executable="6" executed="2" percent="33.33"/>
  <methods count="1" tested="0" percent="0.00"/>
  <functions count="3" tested="2" percent="66.67"/>
  <classes count="1" tested="0" percent="0.00"/>
  <traits count="0" tested="0" percent="0"/>
</totals>
```

✘ We can't stop Infection here, because *we do mutate global anonymous functions* and potentially such mutants can be killed.

There is no way to understand what `functions` are named, what are global AND anonymous, because functions are mentioned like this in `xml` report:

```xml
<function name="foo" signature="foo()" start="3" crap="1" executable="0" executed="0" coverage="100"/>
    <function name="anonymousFunction:4#12" signature="anonymousFunction ()" start="4" crap="1" executable="2" executed="2" coverage="100"/>
    <function name="anonymousFunction:9#33" signature="anonymousFunction (int $number): int" start="9" crap="2" executable="1" executed="0" coverage="0"/>
   
```

#### What I suggest

I suggest to simply ignore 2) and 3) cases and only look at `classes` value in the `xml` report. Thus, if `classes` coverage is `0%`, we stop executing, ignoring global named and anonymous functions. I think this will be 99% of use cases.

Another approach is to not decide by coverage reports, but decide analyzing generated Mutations. Each Mutation has `isCoveredByTest` flag. So if all mutations has `isCoveredByTest=false`, then we can stop creating Mutant processes.

https://github.com/infection/infection/blob/f14fcc5e50da1810e90867e4743a64dbccfbcf72/src/Command/InfectionCommand.php#L225-L229

So the code would be

```php
$coveredByTests = array_filter($mutations, function (Mutation $mutation) {
    return $mutation->isCoveredByTest();
});

if (count($coveredByTests) === 0) {
    throw new NoCoveredByTestsMutationsException(); // Infection stops here
}
```

Bad side of this approach is that we will have to generate all Mutations.

What do you think about guys?

**Comment by sanmai** [comment]
> Another approach is to not decide by coverage reports, but decide by analyzing generated Mutations. Each Mutation has `isCoveredByTest` flag. So if all mutations have `isCoveredByTest=false`, then we can stop creating Mutant processes.

This is the right and proper solution to the problem, in my opinion. But for now IIRC we had only reports concerted with the very first case (`<lines total="21" comments="0" code="21" executable="6" executed="0" percent="0"/>`), so for time being we can safely consider only these two cases.

**Comment by BackEndTea** [comment]
> IIRC for now we had only reports concerted with the very first case (<lines total="21" comments="0" code="21" executable="6" executed="0" percent="0"/>), therefore for time being we can safely consider only this case and only, getting back to more complex solutions later, as a need arise.

I think this is the proper solution, simply check for the percent (or executed) on lines, and if that is 0 bail out, otherwise continue.

>I suggest to simply ignore 2) and 3) cases and only look at classes value in the xml report. Thus, if classes coverage is 0%, we stop executing, ignoring global named and anonymous functions. I think this will be 99% of use cases.

I'm not 100% sure how PHPUnit works with coverage, but i think a class is only considered covered, if every part of it is covered. Which means that if every single class is 95% covered, not a single class is covered according to PHPUnit.

**Comment by localheinz** [comment]
Perhaps it would be possible to make an exception or at least provide an option to not fail with an error if we have no code coverage generated, for example, for a project that has just been set up (where neither production nor test code exist).

What do you think?
