### ISSUE TITLE
Use PHP-Parser 4 to preserve mutated code formatting

### ISSUE THREAD

**Issue by morozov** [infection/infection#55]
Currently, when displaying the difference between original and mutated code, the pretty-formatted representation of the AST is used:

https://github.com/infection/infection/blob/da36bf6a419d9dfc5450eba3d463712440c04023/src/Mutant/MutantCreator.php#L55-L59

Depending on how the original code is formatted, it may lead to the inconsistency between the diff and the original file contents. Additionally, given that `sebastian/diff 2.0` currently doesn't display common lines of code (sebastianbergmann/diff#69), in some cases, the information about how exactly the original code was mutated may be hard to understand.

PHP-Parser 4 introduces the ability to use the [formatting-preserving pretty printing](https://github.com/nikic/PHP-Parser/blob/v4.0.0alpha1/doc/component/Pretty_printing.markdown#formatting-preserving-pretty-printing). Using this kind of formatting together with displaying line numbers may eliminate the need for displaying common lines in the diff.

**Comment by borNfreee** [comment]
Unfortunately, we can't use it right now because of additional formatting of [at least] empty lines.

Here is a result of using new `printFormatPreserving()`:

```diff
--- Original
+++ New
@@ @@
      */
-    public function changeTargetDate(\DateTimeInterface $newTargetDate)
+    protected function changeTargetDate(\DateTimeInterface $newTargetDate)
     {
         \Assert\that($newTargetDate)->greaterOrEqualThan(new \DateTimeImmutable());
-
         $this->targetDate = $newTargetDate;
     }
```

Look at the third line from the end - it is removed while it exists on the original source code.

This bug is currently reproducible for `PublicVisibility` and `ProtectedVisibility` mutators (seems like nested statements of the changed `ClassMethod_` node do not preserve formatting).

I've pushed changes to branch [php-parser-400](https://github.com/infection/infection/tree/php-parser-400) so we can back to it later or if someone wants to play with it. 

I've created an issue in PHP-Parser repository for this case https://github.com/nikic/PHP-Parser/issues/428

**Comment by morozov** [comment]
Cool! I didn't hope it would work right off the bat as it's still in alpha. Thanks for taking a look.

**Comment by borNfreee** [comment]
https://github.com/nikic/PHP-Parser/issues/428 is fixed, so we can continue testing with PHP-Parser 4.0

**Comment by sidz** [comment]
PHP-Parser 4.0 is out. https://github.com/nikic/PHP-Parser/releases/tag/v4.0.0

**Comment by BackEndTea** [comment]
We should definitely support PHP-Parser 4.0. But on the other hand we shouldn't drop support for 3.0. Since most people use infection as a dev-dependency.

**Comment by BackEndTea** [comment]
Moving some comments to this issue, see  https://github.com/infection/infection/pull/201#issuecomment-373421211

* We are using PHP-parser 4.0 now
* We aren't using `printFormatPreserving()` since at the time of writing its not 100% stable yet

Once we are sure that `printFormatPreserving()` is stable enough our minimum requirement of php-parser should be bumped to a version where it is stable, and we should start using it.

**Comment by morozov** [comment]
Closing as fixed by https://github.com/infection/infection/pull/201.
