### ISSUE TITLE
Space in PHP interpreter path breaks Infection

### ISSUE THREAD

**Issue by odinuv** [infection/infection#600]
| Question    | Answer
| ------------| ---------------
| Infection version |  0.11.4
| Test Framework version | PHPUnit 7.5.1
| PHP version | 7.2.2
| Platform | Windows
| Github Repo | https://github.com/keboola/php-temp/tree/ec31be07422ba7dd5f9a5a032929686aaa65abce

Running infection fails when PHP interpreter is located in path containing spaces.

\> php infection.phar

gives:
```
In Process.php line 135:

  The command "C:\Program Files\Php\php.exe D:\php-temp\vendor\phpunit\phpunit\phpunit --version" failed.

  Exit Code: 1(General error)

  Working directory: D:\php-temp

  Output:
  ================


  Error Output:
  ================
  'C:\Program' is not recognized as an internal or external command,
  operable program or batch file.
```

I've traced this down to: https://github.com/infection/infection/blob/7894cf5f6030c3c499004d57f7a29db52aeb2af8/src/TestFramework/AbstractTestFrameworkAdapter.php#L242

where replacing `explode(' ', $phpPath);` with `$this->cachedPhpPath = [$phpPath]`; fixes the problem (but is probably not a solution).

**Comment by sidz** [comment]
@borNfreee 
because of `phpdgb -qrr`
![image](https://user-images.githubusercontent.com/1302230/50792904-947d0280-12d7-11e9-9540-56c8258c0598.png)

When you run Infection with _phpdbg_ we need to add an option -qrr and also https://github.com/symfony/process/blob/master/PhpExecutableFinder.php#L96 symfony finder will add it too.

but we need to pass all arguments separately because symfony/process will execute _escapeArgument_ function to escape each argument: https://github.com/symfony/process/blob/master/Process.php#L294

without this explode we will have
```
array(5) {
  [0]=>
  string(18) "/usr/bin/phpdbg7.2 -qrr"
  [1]=>
  string(49) "/var/www/infection/vendor/phpunit/phpunit/phpunit"
  [2]=>
  string(15) "--configuration"
  [3]=>
  string(57) "/tmp/infection/phpunitConfiguration.initial.infection.xml"
}
```

And the final result will be:
![image](https://user-images.githubusercontent.com/1302230/50793300-cb9fe380-12d8-11e9-8960-03f03147435a.png)
^ which means that commadLine arguments escaped in the wrong way.

**Comment by siad007** [comment]
> 
> 
> Thanks for the explanation.
> 
> Well, if the `phpdbg` is placed in a path with a space, it suffers from the same bug.
> 
> What if we rewrite this part of the code as the following:
> 
> ```
> // $path is "/usr/bin/phpdbg7.2 -qrr"
> 
> if (\PHP_SAPI === 'phpdbg' && substr($path, -4) === '-qrr') {
>     $this->cachedPhpPath = [
>         substr($path, 0, -4), // "/usr/bin/phpdbg7.2"
>         '-qrr'
>     ];
> } else {
>     $this->cachedPhpPath = [$path];
> }
> ```
> 
> ?

Could we not remove the argument handling entirely? See #611

**Comment by sidz** [comment]
@siad007 make sense.
