### ISSUE TITLE
Add support for pcov

### ISSUE THREAD

**Issue by marcospassos** [infection/infection#665]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add support for https://github.com/krakjoe/pcov.

Thank you :)

**Comment by sanmai** [comment]
As I can understand, PHPUnit 8.0 already comes with support for PCOV. So technically you can already use PCOV with Infection, only you would need to generate coverage separately (by running `phpunit --coverage-...` and so on, the usual).

Otherwise put, the issue boils down to Infection not being aware of PCOV as a coverage driver, although I did not test if it is really not aware of it.

**Comment by borNfreee** [comment]
Draft attempt to run Infectino with `pcov` by Joe, for history: https://gist.github.com/krakjoe/8272c747ed247fedbed1c25a2831f09f

**Comment by marcospassos** [comment]
> Otherwise put, the issue boils down to Infection not being aware of PCOV as a coverage driver, although I did not test if it is really not aware of it.
Exactly, infection cannot detect it and fails.
