### ISSUE TITLE
Infection posts no message about executionOrder="random" upon initial test suite failure 

### ISSUE THREAD

**Issue by redaxmedia** [infection/infection#712]
I think Infection should follow the standards of the testing framework it is build on top. The afford to refactor massive testing suites to work in random execution often does not pay off.

It took me time to figure out that I had to set PHPUnit's defaults `executionOrder="default"` inside `phpunit.xml` to have the default behaviour. Seriously, most developers might not expect this!

BTW: I never got this error [message](https://github.com/infection/infection/blob/7894cf5f6030c3c499004d57f7a29db52aeb2af8/src/TestFramework/PhpUnit/Adapter/PhpUnitAdapter.php#L102-L104) - the Infection process exist without showing up an error.

Please keep this issue open and wait for up / downvotes. Thank you!

**Comment by theofidry** [comment]
I would be for PHPUnit to change that default, but one reason why I think it's sensible to do this is that Infection _will_ run tests in a random order. So it's easier to figure out that issue upstream, when running the tests once, rather than when mutating the code.

I believe however we might be missing a case as you should definitely receive that message :)

**Comment by maks-rafalko** [comment]
This is an output for running Infection for itself with a broken test:

<img width="964" alt="executionOrder" src="https://user-images.githubusercontent.com/3725595/59969288-afc08f00-9552-11e9-8c3e-dfa810cd4543.png">

It does show the message mentioned above. Probably, there is a bug, but we need more information to understand how to reproduce it.

What is your PHP / PHPUnit / Infection versions? Do you have a minimal reproducible repository to look at?

---

To be honest, I'm 100% sure we must run tests in a random order if the other value is not set in the project. And the good example is an attempt to add Infection for Psalm: https://github.com/vimeo/psalm/pull/1795#discussion_r294056789

In Psalm, tests fail with a random order, meaning Mutation Testing will give wrong results. That's not what we want. Since Mutation Testing (and Infection in particular) runs tests in a random order (fastest - first) - we need to know project's test suite works with random order without fails.

I'm very sorry you had to spend time understanding what to do, and the message wasn't displayed in your case, but I think we should first understand the reason of it.

**Comment by BackEndTea** [comment]
What version of phpunit are you running? Infection may be unable to figure that out.

**Comment by redaxmedia** [comment]
Your points are totally valid but like I mentioned before: refactoring huge testing suites to run in random order without process isolation everywhere does not pay off in terms of time to investment and slower overall performance.  I tried it but gave up... if Infection would not accept `executionOrder="default"` this would be a red flag to use this project any longer. I guess that I cannot persuade you guys, but from my point of view this is a typical "being a strict vendor" vs. "being a pragmatic user" issue here.

I can only provide the project (a content mangement system) that is causing the error:

## 1. Clone

```
git clone https://github.com/redaxscript/redaxscript.git
```

## 2. Install
```
composer install
```

## 3. Modify
Edit the `executionOrder="default"` inside `phpunit.xml` to random or remove it.

## 4. Run
```
vendor/bin/infection --threads=10 --only-covered
```

**Comment by sanmai** [comment]
See, the whole point in running tests in a random order is to verify that your tests have no hidden dependencies, and that Infection can properly detect all mutations. (I think we should post a warning with this description if `executionOrder` is set to `default`.)

For example, say you have a line covered by tests A, B, and C. Say, Infection changes something in that line, and runs those three tests to see if they caught the change. Now, if any of these tests have a hidden dependency (undeclared, [without `@depends` clause](https://phpunit.readthedocs.io/en/8.2/writing-tests-for-phpunit.html?highlight=depends#writing-tests-for-phpunit-examples-stacktest2-php)), they'll fail, and Infection would thing that these tests are good enough to catch the mutation. But really they're not. This is why it is paramount to have all tests dependencies declared properly. And if you have them as such, then even with `executionOrder="random"` everything will proceed as it should because we specifically ask PHPUnit to respect intertest dependencies.

**Comment by sanmai** [comment]
Not sure if this is a bug or a feature request, but we really should warn people against using `executionOrder="default"`. 

What do you all think?

**Comment by redaxmedia** [comment]
> Really you don't need to refactor anything, all you need is to specify @depends before every test that depends on other test, and that's it.

It is not always that easy and about dependencies - some conflicts happen while working on the same instance of `sqlite:memory` or `$_GLOBALS` that need to be resetted via teardown. Of course everything can be fixed somehow but telling people that there is no need to refactor and invest lot of time is like amarketing promise... :-)

**Comment by sanmai** [comment]
Well, then best you can do is to exclude these fragile tests from being subjected by Infection.

**Comment by theofidry** [comment]
@redaxmedia the thing is, we are not asking this to be purist or strict, but out of necessity. Infection _will_ run your tests in a random order (that's just how the tool works). Sorry that this cannot be addressed differently for now.

A workaround though is as @sanmai mentioned, to manage to isolate those tests to avoid them being run by infection.

**Comment by redaxmedia** [comment]
Thanks guys for keep explaining it over and over... hopefully you can figure out why my testing suite does not throw that error we mentioned above.

**Comment by BackEndTea** [comment]
What exact composer command do you use to install the dependencies? When running composer install in the project you linked, the error does show up.

An edge case may be where infection can't parse the version string of phpunit. 
I'm okay with always showing the warning, or when infection is unable to parse the version.

**Comment by sanmai** [comment]
Well, I do have the message:
```
redaxscript$ php vendor/bin/infection 
You are running Infection with Xdebug enabled.
     ____      ____          __  _
    /  _/___  / __/__  _____/ /_(_)___  ____
    / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
  _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
 /___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Running initial test suite...

PHPUnit version: 8.2.3

   11 [============================] 17 secs
                                                                                                                        
 [ERROR] Project tests must be in a passing state before running Infection.                                             
                                                                                                                        
         Infection runs the test suite in a RANDOM order. Make sure your tests do not have hidden dependencies.         
                                                                                                                        
         You can add these attributes to `phpunit.xml` to check it: <phpunit executionOrder="random"                    
         resolveDependencies="true" ...                                                                                 
                                                                                                                        
         If you don't want to let Infection run tests in a random order, set the `executionOrder` to some value, for    
         example <phpunit executionOrder="default"                                                                      
                                                                                                                        
         Check the executed command to identify the problem: '/tmp/redaxscript/vendor/phpunit/phpunit/phpunit'          
         '--configuration' '/tmp/infection/phpunitConfiguration.initial.infection.xml'                                  
                                                                                                                        
         PHPUnit reported an exit code of 2.                                                                            
                                                                                                                        
         Refer to the PHPUnit's output below:                                                                           
```

**Comment by redaxmedia** [comment]
It is also working for me. Kind of strange! I think back in the days PHPUnit's process silently failed cause of random order and therefore Infection did too.

I cannot reproduce it and would say: issue resolved. Sorry for wasting your time.

**Comment by sanmai** [comment]
I don't think you wasted our time. Your concern is valid, and there's a way to address it.

As it is hard to understand why we're keeping this issue open, as the practical issue there was is no more, I've opened another issue #722 to address that problem with `executionOrder="default"`, so we don't have to drag @redaxmedia along any more.

**Comment by AbdelhakD** [comment]
I hcatch this message and i had also deprecated warning  related to phphunit ProphecyTrait 

After my long Jurney, fixing those worning remove the error and i can continue fixing my TM :)
