### ISSUE TITLE
statistics about the number of usages on corporates in their CI processes

### ISSUE THREAD

**Issue by achrafSallemi** [infection/infection#746]
Hey everyone,
First, I would like to thank everyone who contributed to this amazing project. I was really amazed when running into this Mutation testing library for PHP.
I have a quick question :  How stable **Infection Library** is right now and do you have statistics about the number of usages on corporates in their CI processes ? 

Thanks

**Comment by sanmai** [comment]
It is hard to tell about corporations because they don't report to us, naturally. But you can check [the list of packages that depend on Infection](https://packagist.org/packages/infection/infection/dependents). There are some very high profile packages with tens of millions of installs. Even more packages use Infection as a .phar, so they won't appear in that list. 

Another metric you can look at is the daily installs counter.

**Comment by achrafSallemi** [comment]
That's impressive.
Thanks for the response @sanmai.
