### ISSUE TITLE
Support Github Actions for Mutation Badge

### ISSUE THREAD

**Issue by drupol** [infection/infection#929]
Hello,

The current [BadgeLogger.php](https://github.com/infection/infection/blob/master/src/Logger/BadgeLogger.php) only supports Travis CI for the moment.

How about supporting multiple CI system like:
* Github Actions
* CircleCI
* Drone

I think creating new loggers would be sufficient, what do you think ?

**Comment by maks-rafalko** [comment]
> I think creating new loggers would be sufficient

I would not create additional `**Logger` files, but instead add an abstraction with the common interface here to reuse all existing logic in one `BadgeLogger.php` 

From what I see, for any of the CI platform, we need to know from it

* whether it is PR build or not (we don't want to update MSI on PRs)
* repository slug
* branch name

So we can create an interface and its 2 implementations:

```php
interface CiPlatform {
    public function isPullRequest(): bool;

    public function getRepositorySlug(): string;

    public function getBranchName(): string;
}

class TravisCI implements CiPlatform
{
    public function isPullRequest(): bool
    {
        return getenv('TRAVIS_PULL_REQUEST') === 'true';
    }

    public function getRepositorySlug(): string
    {
        return getenv('TRAVIS_REPO_SLUG');
    }

    public function getBranchName(): string
    {
        return getenv('TRAVIS_BRANCH');
    }
}

class GithubActions implement CiPlatform 
{
    // ...
}
```

Then, `BadheLogger` can be updated to use this interface instead of working with `getenv()`

This will allow adding other CI platform (e.g. CircleCI) by just adding new implementation of the interface (ideally - just one file).

**Comment by drupol** [comment]
I pushed a first commit (WIP), now I need to know how you plan to get the CI autodetection working so I can work on it.

**Comment by rask** [comment]
Status of this? Just set up Github Actions and was met with a blank badge. Did not know that Infection has hardcoded Travis' ENV vars.

**Comment by maks-rafalko** [comment]
Not implemented yet. Subscribe to https://github.com/infection/infection/pull/939

Some base work is almost merged here https://github.com/infection/infection/pull/1047, but additional programming will be required.

**Comment by rask** [comment]
I see, fill follow that. Thanks!

**Comment by rask** [comment]
I see the CI detection feature was implemented, so is this resolved now or is there something hanging which needs to be done still?

**Comment by localheinz** [comment]
@rask 

I guess we only need a new release now!

🤓

**Comment by maks-rafalko** [comment]
The new release (0.16.0) is the biggest one and needs some time yet. I'm planning to tag it ~ next 4 weeks.

You can use master or compile a PHAR for the time being (run `make compile`).

Thank you for understanding ;)

**Comment by rask** [comment]
@localheinz @maks-rafalko I see, great! Will try out an unstable build if I have the time, otherwise I'll wait for a stable release.

Thanks!
