### ISSUE TITLE
[RFC] Mono-repo or not

### ISSUE THREAD

**Issue by theofidry** [infection/infection#930]
As per #922, with the discussion of splitting the test framework bridges, let's make a dedicated RFC about this topic.

Before getting started, it is worth mentioning that the _current_ approach is multi-repo. Indeed we have:

- [infection](https://github.com/infection/infection)
- [infection.github.io](https://github.com/infection/infection.github.io): a readonly "dump" of the site
- [infection/site](https://github.com/infection/site): the actual code of the documentation
- [infection/tests-checker](https://github.com/infection/tests-checker): bot for `infection/infection`
- [homebrew-infection](https://github.com/infection/homebrew-infection): the Homebrew tap

The advantages of the multi-repo is that it's extremely easy to set up: you don't need any additional tooling.

Now what about mono-repositories?

Pros:

- Will make easier any cross-repo changes:
  - if we change the test-framework interface, we can update all the bridges in a compatible way in one go
  - we can more easily have a way to generate parts of the doc or at least keep some elements in sync
  - you can update the code and the doc at the same time in one go
 - You make easier the release process: you can focus on only tagging `infection/infection` and the rest should be tagged at the same time. It avoids to have a lot of different releases for each individual packages the way amphp or Zend has

Cons:

- Requires extra tooling

Now @maks-rafalko also mentioned [this article](https://medium.com/@mattklein123/monorepos-please-dont-e9a279be011b). A few elements regarding the raised points there:

>Monorepo proponents will argue that when all code is present within a single repository, the likelihood of code duplication is small, and it’s more likely that different teams will collaborate together on shared infrastructure.
>Here is the ugly truth about even a medium size monorepo (and this will be a recurring theme throughout this section): it quickly becomes unreasonable for a single developer to have the entire repository on their machine, or to search through it using tools like grep. Thus, any monorepo that hopes to scale must provide two things

I don't know what "medium" size this person is talking about, but I'm aware of several mono-repos with 100-500kLoC and multiple languages and it's neither unreasonable or hard. The only question is how much you are ready to invest in the tooling - and even if you don't go mono-repo, as soon as you have different stacks & techs past a certain size you will need to seriously invest in it anyway.

>Theoretical benefit 2: Single build / no dependency management [...] (proceeds to explain this is a lie)

I won't argue against that: but it's not why we are suggesting a mono-repo either. It is certain though that past a certain size, you want to invest in some tooling to run only the necessary tests. That is however true regardless of the mono-repo or multi-repo choice.

>Downside 1: Tight coupling and OSS
>Organizationally, a monorepo encourages tight coupling and development of brittle software. It gives developers the feeling they can easily fix abstraction mistakes, when they actually cannot in the real world due to the realities of staggered build/deploy and the human/organizational/cultural factors inherent in asking developers to make changes across the entire codebase.

Polyrepos is basically putting a double lock here: if you have a well defined and stable boundary that makes it easier to enforce and respect it, but if you get it wrong or need to change it you are also making it much harder. IMO it's a debate worth having with your team, but ultimately it's a culture/process issue: I've seen teams recreating a library in-house to by-pass the dedicate package because it was "easier" for them (and that was enabled by the lack of control). So in other words, those physical boundaries won't fix it all for you.

>Downside 2: VCS scalability

Well we're not at the millions LoC scale and I can vouch for the performance for up to a few hundred thousands LoC so I don't think it's a problem in practice for us.

**Comment by maks-rafalko** [comment]
2 cents from me at this point:

Even if we how with monorepo, we should not merge all the repositories mentioned above into one:
  * _[infection.github.io](https://github.com/infection/infection.github.io): a readonly "dump" of the site_ - this is a result of compiled (generated) documentation, no need to have it inside monorepo
  * _[infection/site](https://github.com/infection/site): the actual code of the documentation_ - this is a quite big **Javascript/CSS** application with binary tooling (`hexo`). IMO, no need to have it inside monorepo
  * _[infection/tests-checker](https://github.com/infection/tests-checker): bot for `infection/infection`_ - this is a **TypeScript** application that has nothing common with Infection. No need to have it inside monorepo
  * _[homebrew-infection](https://github.com/infection/homebrew-infection): the Homebrew tap_ - this is a **Ruby**  repository - again, nothing common with Infection test framework. No need to have it inside monorepo.

Keeping that in mind, I would say that we should talk only about the following repositories when we discuss monorepo:

* `infection/infection` (existing)
* `infection/abstract-testframework-adapter` (in progress)
* `infection/phpunit-adapter`  (in progress)
* `infection/phpspec-adapter`  (in progress)
* `infection/codeception-adapter`  (in progress)

But Bots, JS static side generators, ruby Homebrew formulas - all of that is not needed in the monorepo.

---

Some of the concerns I found recently:

* When you open a monorepo in the IDE, you will have N `vendor` folders which makes PHPStorm indexing all of them, and in its turn making autocomplete a mess. Currently, I'm experiencing exactly the same issue on my daily job - we have 3 Symfony applications inside the same repository (kind of monorepo, but without splitting and tagging packages separately).

  If monorepo does not suggest opening the root repository in IDE (which contains N packages) - then I don't understand how it should work from developer point of view. Should I open N projects in PHPStorm? What about "git root"? what about commands that need to be run from the root? etc.

* Releasing. As far as I understand from [this thread](http://disq.us/p/25g8x80), monorepo uses "united versioning". 

  > You make easier the release process: you can focus on only tagging infection/infection and the rest should be tagged at the same time.
 
  This is incompatible with the Package Design I would say. We need a way to have _separate_ versioning for each package. When PHPUnit adapter has a bug or has a BC break - I want to release only PHPUnit adapter with a patch (or major) release, but not all the packages.

* Tooling. Before deciding, everyone from us should understand what tools we are going to use and what issues we can face with (like releasing / tagging and so on). As I see - there are several tools alternatives. I didn't have experience with any of them, so personally I wouldn't treat my comment as "yes" or "now" since I completely don't understand how it works under the hood atm.

**Comment by theofidry** [comment]
>Even if we go with monorepo, we should not merge all the repositories mentioned above into one:

Maybe not all, but personally I would see the benefit for the documentation. Sure the JS/CSS might seem unnecessary, but at the end of the day the most important part of it is the documentation and it's way easier to:

- contribute to the doc when adding a new feature if you can do it at the same time in the same repo
- add extra tools for keeping in sync or generate part of the doc based on the doc if it's within the same repo (it would be quite hard to achieve right now)

In fact even with the homebrew tap it might have value as it might be easier to update the formula that way.

In any case: I'm not saying it's because we go mono-repo that we need to merge everything in one. It however opens the door to do so if there is a value in it.

>If monorepo does not suggest opening the root repository in IDE (which contains N packages) - then I don't understand how it should work from developer point of view. Should I open N projects in PHPStorm? What about "git root"? what about commands that need to be run from the root? etc.

Some IDEs like Xcode offer better workspace support than other and we don't really have an equivalent yet in the PHP ecosystem. But personally I mostly do with the "warnings" because I get them regularly anyway be it infection or PhpScoper due to the fixtures which may contain vendors as well.

>This is incompatible with the Package Design I would say. We need a way to have separate versioning for each package. When PHPUnit adapter has a bug or has a BC break - I want to release only PHPUnit adapter with a patch (or major) release, but not all the packages.

It may be a violation of package design but that's where you got to pick between purity and pragmatism. In practice it does pose any other problem that eventually creating an "empty" release and that's what you get when you consume Symfony or Laravel packages. I'm not saying it's perfect, it's not, but from my PoV it is much more practical than the Amphp, Zend or httplug where both from a consumer and a release process it's quite the headache.

**Comment by maks-rafalko** [comment]
> contribute to the doc when adding a new feature if you can do it at the same time in the same repo

Having `*.md` files is ok in the monorepo, but adding the whole JS application will lead to adding all the not needed files, including `node_modules` (after `yarn install`) to IDE which again will add unnecessary resource consumption and noise during file searching, autocompleting, etc. My PHPStorm app with 3 SF applications already eats ~5Gb of memory.

> It may be a violation of package design but that's where you got to pick between purity and pragmatism.

Well, for me it's a red flag. Package Design RFC is intended to bring all the benefits from the theory to practise, including separate versioning and absence of _irrelevant_ changes for the end user, but seems like monorepo just brings it back, offering empty releases. I definitely don't like it.

Imagine the users who runs `composer outdated` and see there is a major release for `PHPUnit` adapter. They go to `CHANGELOG.md` and see empty changelog with no changes in the code :|

Moreover, they will need to update `^1.0.0` to `^2.0.0` in their `composer.json` without any reason.

**Comment by theofidry** [comment]
>Well, for me it's a red flag. Package Design RFC is intended to bring all the benefits from the theory to practise, including separate versioning and absence of irrelevant changes for the end user, but seems like monorepo just brings it back, offering empty releases. I definitely don't like it.

I might be biased, for me that's one of the thing both Laravel and Symfony got right that boosted their productivity and there is no doubt within the Symfony core team that they would not be able to maintain their contribution level that high with polyrepo. It's also not a PHP thing: look at Rails, Django, Angular... And on a personal level I stopped myself to contribute/involve myself in a number of projects because it required me to touch 3-5 different repositories.

Anyway it's my PoV and my point. We can disagree on it and that's fine but I would like it at least to be a team decision as it affects all of us and also all the actual & future contributors

**Comment by sanmai** [comment]
I'm definitely against merging existing repositories. They're independent from each other, and that's a gold standard for splitting projects as I see it.

Regarding splitting the main repository, first I'd address this claim:

> Organizationally, a monorepo encourages tight coupling and development of brittle software.

This is not true because tight coupling is a thing that exists in minds, not in repositories. We have numerous examples where _very_ distributed projects were exceptionally tightly coupled. Say, in PHP ecosystem we have PEAR with its base PEAR class on which almost everything depends. 

But that's not a prime example because we also have [Hoa project](https://github.com/hoaproject) which has many projects depending on each other so much that the whole project is basically stalled since 2018. It's just so much political power required to update multiple interdependent projects. (I had a hands-on experience separating, or even salvaging, [hoa-compiler](https://github.com/sanmai/hoa-compiler) from that ecosystem deadlock.)

If we ever to split Infection into many sub-projects, then...
- This has to be done very cautiously, and with regard to a practical need. If there isn't a concrete practical need, it may not be the best idea to extract things. E.g. for #669 we have empirical evidence that there are possible users for this kind of sub-project.
- This should not introduce circular dependencies. E.g. every sub-project must be still possible to update and work on without any need to update the root project. #922 may stumble on this issue.

**Comment by maks-rafalko** [comment]
>  [...] E.g. every sub-project must be still possible to update and work on without any need to update the root project. #922 may stumble on this issue.

In which way? As I said in RFC ticket - there will be no circular dependency as this is a violation of corresponded package design principle.

> Say, you have infection/phpunit-adapter, and naturally you want to test in with Infection. And then what? How do you introduce breaking changes?

For adapter, breaking changes can only be inside abstraction - `infection/abstract-test-framework`. There is no other "touch point" between adapter and `infection/infection`. And this is a key thing.

When we want to introduce BC break in `infection/abstract-testframework-adapter`, that we will need to bump major version for abstraction, for adapterm for infection, because contract is changed. Previous version are still compatible. New - works with new contract.

> Are you going to make a small release to test against every breaking change?

No, you will be working on infection `master` and pull adapter's `master` (or any other version)

**Comment by sanmai** [comment]
> No, you will be working on infection master and pull adapter's master (or any other version)

So are you going to introduce `dev-master` dependencies to `composer.json`?
If any other version, will that be reflected in the build matrix? How big will it be?

> no circular dependency

And no integration testing against other packages, am I right?

**Comment by maks-rafalko** [comment]
I answered to you question here: https://github.com/infection/infection/issues/922#issuecomment-570076331

Let's keep this this issue for Monorepo vs Multirepo topic.

For @infection/core - we still need other's opinion if you have one.
