### ISSUE TITLE
Mutations not working well with function_exists

### ISSUE THREAD

**Issue by BackEndTea** [infection/infection#97]
| Question    | Answer
| ------------| ---------------
| Infection version | 0.7.0
| Test Framework version | PHPUnit/ 6.5.-
| PHP version | 7.1.12
| Platform    | MacOS
| Github Repo | https://github.com/BackEndTea/Array-Meta

<details>
 <summary>Output with issue</summary>
Given the following source code

```php
<?php

declare(strict_types=1);

if (!\function_exists('isValidArrayKey')) {
    function isValidArrayKey($key): bool
    {
        return \is_string($key) || \is_int($key);
    }
}
```

I expected these tests to cover everything
```php
<?php

declare(strict_types=1);

namespace BackEndTea\ArrayMeta\Test\Unit;

use BackEndTea\ArrayMeta\Test\Fixture\KeyExceptionFixture;

class HelpersTest extends \PHPUnit\Framework\TestCase
{
    public function testIsValidArrayKeyReturnsTrueWhenSuppliedWithInteger()
    {
        $this->assertTrue(isValidArrayKey(3));
    }

    public function testIsValidArrayKeyReturnsTrueWhenSuppliedWithString()
    {
        $this->assertTrue(isValidArrayKey('key'));
    }

    /**
     * @param $key
     *
     * @dataProvider provideInvalidKeysForIsValidArrayTest
     */
    public function testIsValidArrayKeyReturnsFalseWhenSuppliedWithInvalidKey($key)
    {
        $this->assertFalse(isValidArrayKey($key));
    }

    public function provideInvalidKeysForIsValidArrayTest(): array
    {
        return [
            [new \stdClass()],
            [2.5],
            [new KeyExceptionFixture()],
            [array()],
            [null],
        ];
    }
}
```

However, it tells me the following mutation does not get covered
```diff
1) /Users/Ibuildings/Projects/ArrayWrap/src/helpers.php:8    [M] LogicalOr
exec /usr/local/Cellar/php71/7.1.12_23/bin/php -c /private/var/folders/5y/g0yc55n12hjcc4zb0k3z2x_m0000gn/T/infectionY1rj3s /Users/Ibuildings/Projects/ArrayWrap/vendor/phpunit/phpunit/phpunit --configuration /var/folders/5y/g0yc55n12hjcc4zb0k3z2x_m0000gn/T/infection/phpunitConfiguration.9263c2c2e35e7efa3a1cebf954bdba92.infection.xml --stop-on-failure 
--- Original
+++ New
@@ @@
-        return \is_string($key) || \is_int($key);
+        return \is_string($key) && \is_int($key);

PHPUnit 6.5.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.12
Configuration: /private/var/folders/5y/g0yc55n12hjcc4zb0k3z2x_m0000gn/T/infection/phpunitConfiguration.9263c2c2e35e7efa3a1cebf954bdba92.infection.xml

.......                                                             7 / 7 (100%)

Time: 18 ms, Memory: 4.00MB

OK (7 tests, 7 assertions)
```

My guess is that because of the ```if (!\function_exists('isValidArrayKey')) {``` It keeps calling the original function
</details>

**Comment by BackEndTea** [comment]
I tested it with the following function
```php
if (!\function_exists('alwaysReturnTrue')) {
    function alwaysReturnTrue()
    {
        return true;
    }
}
```
and the following test
```php
public function testReturnTrue()
{
    $this->assertTrue(alwaysReturnTrue());
 }
```
And once again the mutant is escaped
```diff
2) /Users/Ibuildings/Projects/ArrayWrap/src/helpers.php:15    [M] TrueValue
exec /usr/local/Cellar/php71/7.1.12_23/bin/php -c /private/var/folders/5y/g0yc55n12hjcc4zb0k3z2x_m0000gn/T/infectionlUAi7m /Users/Ibuildings/Projects/ArrayWrap/vendor/phpunit/phpunit/phpunit --configuration /var/folders/5y/g0yc55n12hjcc4zb0k3z2x_m0000gn/T/infection/phpunitConfiguration.faffa38c815fc8155cc22ff9e63995f7.infection.xml --stop-on-failure 
--- Original
+++ New
@@ @@
-        return true;
+        return false;

PHPUnit 6.5.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.12
Configuration: /private/var/folders/5y/g0yc55n12hjcc4zb0k3z2x_m0000gn/T/infection/phpunitConfiguration.faffa38c815fc8155cc22ff9e63995f7.infection.xml

........                                                            8 / 8 (100%)

Time: 18 ms, Memory: 4.00MB

OK (8 tests, 8 assertions)
```

**Comment by theofidry** [comment]
Probably related to https://github.com/humbug/humbug/issues/194

**Comment by borNfreee** [comment]
Thanks for creating this bug report @BackEndTea.

Well, there are at least 2 possible ways to proceed:

1. Do not mutate functions like it was done in Humbug (see the link from Theo's comment above)
2. Fix this issue by some dirty hack

About the second point:

PHP currently does not have autoloading for functions, so files with them are loaded through composer's `files` feature.

The reason of this bug is that PHPUnit/PHPSpec always load composer's `autoload.php` file first, which in its turn loads `files` from project's `composer.json`. It means functions from the mutated file are ignored because `function_exists` always returns true.

What we can do is to wrap `bin/phpunit` or `bin/phpspec` with our own bootstrap file to do the following:

```bash
# /var/tmp/phpunit-custom-bin

# first - load our mutated file with functions
require '/project/root/src/helpers.php';

# then load PHPUnit which loads vendor/autoload.php
require '/project/root/vendor/bin/phpunit';
```

and Infection will run PHPUnit as `/var/tmp/phpunit-custom-bin ...` instead of just `/project/root/vendor/bin/phpunit`.

Potential bugs: if user function is not wrapped with `if (! function_exists()) {}` then we will have an error. We can solve this issue though with additional analyzing/parsing.

I would vote for disabling mutations of files with custom functions since such files (from my experience) are not often used or do not contain a much code.

Any thoughts?

**Comment by theofidry** [comment]
It's a limitation we can work on at some point but I would leave it for now 👍

**Comment by BackEndTea** [comment]
For my project ive excluded it. Short term id say just not mutating them would be best. But keep it in mind as an option for the future
